# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Greenkeeper < Formula
  desc "Background daemon that dispatches AI agents to fix your GitHub PRs"
  homepage "https://github.com/RussellBloxwich/greenkeeper"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RussellBloxwich/greenkeeper/releases/download/v0.2.0/greenkeeper_darwin_amd64.tar.gz"
      sha256 "c5fad550a0ad1d864489373ddb041a6658b509af9f8566d90d2bf1f707dd45ec"

      define_method(:install) do
        bin.install "greenkeeper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RussellBloxwich/greenkeeper/releases/download/v0.2.0/greenkeeper_darwin_arm64.tar.gz"
      sha256 "b49c7eee1c30fe1d7b84ac268849f3e8777d0505d08655128d2c03c0e3e5f679"

      define_method(:install) do
        bin.install "greenkeeper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RussellBloxwich/greenkeeper/releases/download/v0.2.0/greenkeeper_linux_amd64.tar.gz"
      sha256 "2f935ad689d9796ddffef65bd1f2c576f4d94e066e9d352576cb17cce8cadd28"
      define_method(:install) do
        bin.install "greenkeeper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RussellBloxwich/greenkeeper/releases/download/v0.2.0/greenkeeper_linux_arm64.tar.gz"
      sha256 "a80f7a68985f413543760a17bca04b40296e3f8529f553ee12996a5ab71a3e63"
      define_method(:install) do
        bin.install "greenkeeper"
      end
    end
  end

  test do
    system "#{bin}/greenkeeper", "version"
  end
end
