# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Greenkeeper < Formula
  desc "Background daemon that dispatches AI agents to fix your GitHub PRs"
  homepage "https://github.com/RussellBloxwich/greenkeeper"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RussellBloxwich/greenkeeper/releases/download/v0.1.0/greenkeeper_darwin_amd64.tar.gz"
      sha256 "3f85b25e755f6d1e2b2dd9da2357a46f538feac851ac17188def93f3fc358ea2"

      define_method(:install) do
        bin.install "greenkeeper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RussellBloxwich/greenkeeper/releases/download/v0.1.0/greenkeeper_darwin_arm64.tar.gz"
      sha256 "55d332207b7a4bde3f989ef8d2d69f0f9b0606824723f1ddd4445d53737c3bc7"

      define_method(:install) do
        bin.install "greenkeeper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RussellBloxwich/greenkeeper/releases/download/v0.1.0/greenkeeper_linux_amd64.tar.gz"
      sha256 "b2e79ec756e45b2f0d8ad6d42b885719eea1f0ed80ee0b957bca06d4cadefeec"
      define_method(:install) do
        bin.install "greenkeeper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RussellBloxwich/greenkeeper/releases/download/v0.1.0/greenkeeper_linux_arm64.tar.gz"
      sha256 "16c442cc13850cc06499914c6d38c34449b1ed64d83d4ea2c30a6136b6fd8272"
      define_method(:install) do
        bin.install "greenkeeper"
      end
    end
  end

  test do
    system "#{bin}/greenkeeper", "version"
  end
end
