# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Greenkeeper < Formula
  desc "Background daemon that dispatches AI agents to fix your GitHub PRs"
  homepage "https://github.com/RussellBloxwich/greenkeeper"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RussellBloxwich/greenkeeper/releases/download/v0.2.1/greenkeeper_darwin_amd64.tar.gz"
      sha256 "bf0cf98c4b82d24274a66b521e3b7df642f4aba312e65731b476fea14bb0a202"

      define_method(:install) do
        bin.install "greenkeeper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RussellBloxwich/greenkeeper/releases/download/v0.2.1/greenkeeper_darwin_arm64.tar.gz"
      sha256 "837b35724d3b4d6c1bf8973346b5db8a944b361a9d763f510f6ce7a0273bb9fa"

      define_method(:install) do
        bin.install "greenkeeper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RussellBloxwich/greenkeeper/releases/download/v0.2.1/greenkeeper_linux_amd64.tar.gz"
      sha256 "f18f1718b823c7a765dd0fae5dbb0b20770e4835c60f9d7e9308c202bb0f0f55"
      define_method(:install) do
        bin.install "greenkeeper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RussellBloxwich/greenkeeper/releases/download/v0.2.1/greenkeeper_linux_arm64.tar.gz"
      sha256 "1d8aaba64becea22b126da31d9bbcf53e7b2549557a7f3bc049d63a7ecf35369"
      define_method(:install) do
        bin.install "greenkeeper"
      end
    end
  end

  test do
    system "#{bin}/greenkeeper", "version"
  end
end
